version: '3.7'

volumes:
  orderer0.fh-orderer.pemilwa.com:
  peer0.fh.pemilwa.com:
  peer1.fh.pemilwa.com:

networks:
  pemilwa:
    external: true
    name: fabric-pemilwa

services:

  orderer0-fh:
    image: hyperledger/fabric-orderer:2.5.10
    labels:
      service: hyperledger-fabric
    hostname: orderer0.fh-orderer.pemilwa.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_LOCALMSPID=fh-ordererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.fh-orderer.pemilwa.com:10443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
        - /home/ubuntu/network/fabric/organizations/ordererOrganizations/fh-orderer.pemilwa.com/orderers/orderer0.fh-orderer.pemilwa.com/msp:/var/hyperledger/orderer/msp
        - /home/ubuntu/network/fabric/organizations/ordererOrganizations/fh-orderer.pemilwa.com/orderers/orderer0.fh-orderer.pemilwa.com/tls/:/var/hyperledger/orderer/tls
        - orderer0.fh-orderer.pemilwa.com:/var/hyperledger/production/orderer
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.hostname == vm2
    ports:
      - 8050:8050
      - 8053:8053
      - 10443:10443
    networks:
      pemilwa:
        aliases:
          - orderer0.fh-orderer.pemilwa.com

  peer0-fh:
    image: hyperledger/fabric-peer:2.5.10
    labels:
      service: hyperledger-fabric
    hostname: peer0.fh.pemilwa.com
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-pemilwa
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.fh.pemilwa.com
      - CORE_PEER_ADDRESS=peer0.fh.pemilwa.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.fh.pemilwa.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fh.pemilwa.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fh.pemilwa.com:8051
      - CORE_PEER_LOCALMSPID=fhMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.fh.pemilwa.com:10444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0fh"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      #CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0fh:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /root
    command: peer node start
    volumes:
      - /home/ubuntu/network/fabric/organizations/peerOrganizations/fh.pemilwa.com/peers/peer0.fh.pemilwa.com:/etc/hyperledger/fabric
      - peer0.fh.pemilwa.com:/var/hyperledger/production
      - /home/ubuntu/network/fabric/config:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.hostname == vm2
    ports:
      - 8051:8051
      - 10444:10444
    networks:
      pemilwa:
        aliases:
          - peer0.fh.pemilwa.com

  peer1-fh:
    image: hyperledger/fabric-peer:2.5.10
    labels:
      service: hyperledger-fabric
    hostname: peer1.fh.pemilwa.com
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-pemilwa
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.fh.pemilwa.com
      - CORE_PEER_ADDRESS=peer1.fh.pemilwa.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer1.fh.pemilwa.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.fh.pemilwa.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fh.pemilwa.com:11051
      - CORE_PEER_LOCALMSPID=fhMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.fh.pemilwa.com:13444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1fh"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      #CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1fh:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /root
    command: peer node start
    volumes:
      - /home/ubuntu/network/fabric/organizations/peerOrganizations/fh.pemilwa.com/peers/peer1.fh.pemilwa.com:/etc/hyperledger/fabric
      - peer1.fh.pemilwa.com:/var/hyperledger/production
      - /home/ubuntu/network/fabric/config:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.hostname == vm2
    ports:
      - 11051:11051
      - 13444:13444
    networks:
      pemilwa:
        aliases:
          - peer1.fh.pemilwa.com